name: 🪲 Bug Report
description: Know of an issue with this project? Submit a bug report.
type: "Bug"
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please provide detailed information to help us reproduce and fix the issue. The more details you provide, the faster we can resolve it.
           
  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected behaviour
      description: Describe what you expected to happen.
      placeholder: Enter the expected behaviour
    validations:
      required: true

  - type: textarea
    id: actual_behaviour
    attributes:
      label: Actual behaviour
      description: Describe what actually happened.
      placeholder: Enter the actual behaviour
    validations:
      required: true      
  
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug.
      placeholder: Enter the steps to reproduce the bug
      value: |
        _N/A_
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: Add any screenshots or logs that might help identify the issue.
      placeholder: Provide any screenshots or logs (if applicable)
      value: |
        _N/A_
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Include any additional context or relevant information
      value: |
        _N/A_
    validations:
      required: false
